name = "blog_admin"
main = "src/index.tsx"
node_compat = true
compatibility_date = "2023-01-22"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "synopsis"
database_id = "b007b6bc-bb26-4fa3-8ded-ead469ceb097"
preview_database_id = "d93d157f-34f9-4212-bad4-9a1d89ff3b81"

[site]
bucket = "./assets"

[vars]

services = [
  { binding = "SYNOPSIS", service = "synopsis", environment = "production" }
]