name = "blog_admin"
main = "src/index.ts"
node_compat = true

compatibility_date = "2023-01-22"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "synopsis"
database_id = "b007b6bc-bb26-4fa3-8ded-ead469ceb097"

[vars]
ACCESS_TOKEN = "example_dev_token"